version: '3.8'
services:
  mysql:
    image: mysql:8
#    container_name: realmon-mysql
    environment:
      MYSQL_ROOT_PASSWORD: wulin9786
      MYSQL_DATABASE: realmondb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  realmon-backend:
    build:
      context: ./realmon-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/realmondb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: wulin9786

volumes:
  mysql_data:
