spring:
  datasource:
    url: jdbc:mysql://mysql:3306/realmondb?useSSL=false&serverTimezone=UTC
    username: root
    password: wulin9786
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8080