# Copy this file to application-local.yml and fill in your actual environment variables

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/realmondb?useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
