server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update # used to update databases based on entities
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  profiles:
    active: local


