server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update # used to update databases based on entities
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect

  profiles:
    active: local


